### ISSUE TITLE
Audit k2cli cobra usage

### ISSUE THREAD

**Issue by davidewatson** [samsung-cnct/kraken#46]
New:

All k2cli cobra usage should be audited to be consistent.

Old:

When a config file is not specified, k2cli panics instead of assuming the default location like the other commands do.

```
rodin:k2cli dwat$ k2cli tool ssh update
Pulling image 'quay.io/samsung_cnct/k2:latest' ███▒▒▒▒▒▒▒ 
Updating ssh inventory for '' panic: runtime error: index out of range

goroutine 1 [running]:
panic(0x431b00, 0xc4200120e0)
	/usr/local/Cellar/go/1.7.3/libexec/src/runtime/panic.go:500 +0x1a1
github.com/samsung-cnct/k2cli/cmd.glob..func15(0x6eb0c0, 0x70f540, 0x0, 0x0)
	/Users/dwat/workspace/go/src/github.com/samsung-cnct/k2cli/cmd/ssh-update.go:50 +0xa24
github.com/samsung-cnct/k2cli/vendor/github.com/spf13/cobra.(*Command).execute(0x6eb0c0, 0x70f540, 0x0, 0x0, 0x6eb0c0, 0x70f540)
	/Users/dwat/workspace/go/src/github.com/samsung-cnct/k2cli/vendor/github.com/spf13/cobra/command.go:636 +0x443
github.com/samsung-cnct/k2cli/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x6e9fc0, 0xc420177ee8, 0x5f5b, 0xc4200160b8)
	/Users/dwat/workspace/go/src/github.com/samsung-cnct/k2cli/vendor/github.com/spf13/cobra/command.go:722 +0x367
github.com/samsung-cnct/k2cli/vendor/github.com/spf13/cobra.(*Command).Execute(0x6e9fc0, 0xc4200deb40, 0x0)
	/Users/dwat/workspace/go/src/github.com/samsung-cnct/k2cli/vendor/github.com/spf13/cobra/command.go:681 +0x2b
github.com/samsung-cnct/k2cli/cmd.Execute()
	/Users/dwat/workspace/go/src/github.com/samsung-cnct/k2cli/cmd/root.go:63 +0x31
main.main()
	/Users/dwat/workspace/go/src/github.com/samsung-cnct/k2cli/main.go:23 +0x22
rodin:k2cli dwat$ 
```

**Comment by joejulian** [comment]
Also 
```
k2cli cluster up ${HOME}/k2configs/config.yaml
```
vs
```
k2cli tool kubectl --config ${HOME}/k2configs/config.yaml get nodes
```

`--config` should be a general option that is used for all k2cli commands.

**Comment by alejandroEsc** [comment]
Not sure i understand why this ticket is still open. Can i get a few more details about what is still needed?

**Comment by coffeepac** [comment]
this ticket is still open because its mostly been forgotten.  i think the work you've done over the past month has probably covered most of what we wanted to get done here.

@davidewatson anything else or are you happy to close this?
